version: '3'

services:
  spark-master:
    image:  bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./data:/app/data
    networks:
      - spark-network

  spark-worker:
    image:  bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./data:/app/data
    depends_on:
      - spark-master
    networks:
      - spark-network

  scytale-etl:
    build:
      context: /src
      dockerfile: dockerfile
    container_name: scytale-etl
    environment:
      - GITHUB_TOKEN=<Your-Git-Token>
      - organization=Scytale-exercise
      - SPARK_MODE=remote
      - SPARK_MASTER_URL=spark://spark-master:7077  # Only used if SPARK_MODE is 'remote'
    volumes:
      - ./data:/app/data
    depends_on:
      - spark-master
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
