FROM openjdk:8-jdk-slim

# Install Python and other dependencies
RUN apt-get update && apt-get install -y python3 python3-pip curl && \
    apt-get clean

# Install Spark
ENV SPARK_VERSION=3.5.0
ENV HADOOP_VERSION=3
RUN curl -L https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz | \
    tar -xz -C /opt/ && \
    mv /opt/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} /opt/spark

# Set environment variables
ENV SPARK_HOME=/opt/spark
ENV PATH=$PATH:$SPARK_HOME/bin

# Copy application code
COPY . /app
WORKDIR /app

# Install the Python dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r ./requirements.txt

# Set entrypoint
ENTRYPOINT ["python3", "etl.py"]